// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cheqvbtsgehxjpcfnwhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZXF2YnRzZ2VoeGpwY2Zud2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTkwMTksImV4cCI6MjA1ODczNTAxOX0.SPpR3NIlTW9zDPAEBP_mBQ4oJiBVYoqLFo-mUZbb_aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);